swagger: "2.0"
info:
  title: "Esercizio 1 Esame 02/01/2021"
  version: 1.0.0 
  description: "API per la gestione di un parco auto"
paths:
  /parco/automobili:
    get:
      description: "Get di tutte le automobili presenti"
      operationId: getAutomobili
      parameters:
        - in: query
          required: false
          name: annoImmatricolazioneMinimum
          type: integer
          format: int32
      responses:
        '200':
          description: "Success"
          schema:
            type: array
            items:
              type: object
              $ref: "#/definitions/Automobile"
        '400':
          description: "Failed parametri di input non corretti"
  /parco/automobili/{targaAutomobile}:
    put:
      description: "Update della descrizione di un'automobile"
      operationId: updateDescrizione
      parameters:
        - in: path
          required: true
          name: targaAutomobile
          type: string
        - in: body
          required: true
          name: nuovaDescrizione
          schema: 
            type: string
            example: "Berlina rossa sportiva"
      responses:  
        '200':
          description: "Success"
        '400':
          description: "Failed parametri di input non corretti"
definitions:
  Automobile:
    type: object
    required: 
      - targa
      - descrizione
      - annoImmatricolazione
    properties:
      targa:
        type: string
        example: "CA070CA"
      descrizione:
        type: string
        example: "Berlina sportiva"
      annoImmatricolazione:
        type: integer
        format: int32
        example: 2021