swagger: "2.0"
info:
  title: "API per la gestione di una spiaggia"
  version: 1.0.0
paths:
  /spiaggia/stabilimenti/{numeroStabilimento}/:
    put:
      description: "Update della descrizione di uno stabilimento"
      operationId: updateDescrizioneStabilimento
      parameters:
        - in: path
          required: true
          name: numeroStabilimento
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovaDescrizione
          schema:
            type: string
            example: "Stabilimento con una vista mozzafiato"
      responses:
        '200':
          description: "Success descrizione aggiornata"
        '400':
          description: "Failed parametri in input non corretti"
    get:
      description: "Get di tutti gli ombrelloni liberi"
      operationId: getOmbrelloniLiberi
      parameters:
        - in: path
          required: true
          name: numeroStabilimento
          type: integer
          format: int32
        - in: query
          required: true
          name: statoOmbrelloni
          type: string
          enum:
            - "libero"
            - "occupato giornaliero"
            - "occupato stagionale"
      responses:
        '200':
          description: "Success ombrelloni individuati"
          schema: 
            type: array
            items:
              $ref: "#/definitions/Ombrellone"
        '400':
          description: "Failed parametri in input non corretti"
  /spiaggia/stabilimenti/{numeroStabilimento}/ombrelloni/:
    post:
      description: "Add di un ombrellone allo stabilimento"
      operationId: addOmbrellone
      parameters:
        - in: path
          required: true
          name: numeroStabilimento
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovoOmbrellone
          schema:
            type: object
            $ref: "#/definitions/Ombrellone"
      responses:
        '200':
          description: "Success ombrellone aggiunto"
          schema: 
            type: object
            $ref: "#/definitions/Ombrellone"
        '400':
          description: "Failed parametri in input non corretti"
definitions:
  Stabilimento:
    type: object
    required: 
      - numeroStabilimento
      - nome 
      - descrizione
    properties:
      numeroStabilimento:
        type: integer
        format: int32
        example: 1
      nome:
        type: string
        example: "Le Dune Beach"
      descrizione:
        type: string
        example: "Stabilimento super attrezzato"
  Ombrellone:
    type: object
    required: 
      - numeroOmbrellone
      - stato
    properties:
      numeroOmbrellone:
        type: integer
        format: int32
        example: 7
      stato:
        type: string
        enum: 
          - "libero"
          - "occupato giornaliero"
          - "occupato stagionale"
        example: "libero"
