swagger: "2.0"
info: 
  title: "Esercizio 1 Esame 01/01/2023"
  description: "API per la gestione di un parco auto"
  version: 1.0.0
paths:
  /parco/automobili/:
    get:
      description: "Get di tutte le auto presenti"
      operationId: getAutomobiliFromParco
      parameters:
        - in: query
          required: false
          name: annoImmatricolazione
          type: integer
          format: int32
      responses:
        '200':
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Automobile"
        '400':
          description: "Failed"
  /parco/automobili/{targaAutomobile}/:
    put:
      description: "Update della descrizione di un auto"
      operationId: updateDescrizioneAutomobile
      parameters: 
        - in: path
          required: true
          name: targaAutomobile
          type: string
        - in: body
          required: true
          name: nuovaDescrizione
          schema:
            type: string
            example: "Berlina rossa sportiva"
      responses:  
        '200':  
          description: "Success"
        '400':  
          description: "Failed"
definitions:
  Automobile:
    type: object
    required:
      - targa
      - descrizione
      - annoImmatricolazione
    properties:
      targa:
        type: string
        example: "CA070CA"
      descrizione:
        type: string
        example: "Auto blu sportiva"
      annoImmatricolazione:
        type: integer
        format: int32
        example: 2021