swagger: "3.0"
info:
  title: "API per la getsione di un parco auto"
  version: 1.0.0
paths:
  /parco/automobili/:
    get:
      summary: "Get di tutte le auto presenti nel parco auto"
      operationId: getCars
      parameters:
        - in: query
          required: false
          name: annoImmatricolazione
          type: integer
          format: int32
          schema: 
            type: integer
            example: 2021
      responses:
        '200':
          description: "Success auto presenti all'interno del parco auto"
          schema:
            type: array
            items:
              $ref: "#/definitions/Automobile"
        '400':
          description: "Failed nessuna auto presente nel parco auto"
  /parco/automobili/{targaAutomobile}/:
    put:
      summary: "Put di una descrizione per una determinata auto"
      operationId: updateDescription
      parameters:  
        - in: path
          required: true
          name: targaAutomobile
          type: string
        - in: body
          required: true
          name: descrizioneAutomobile
          schema:
            type: string
            example: "Auto familiare di colore giallo"
      responses:
        '200':
          description: "Success descrizione aggiornata con successo"
        '400':
          description: "Failed descrizione non aggiornata"
definitions:
  Automobile:
    type: object
    required:
      - targa
      - descrizione
      - annoImmatricolazione
    properties:
      targa:
        type: string
        example: "CA070CA"
      descrizione:
        type: string
        example: "Auto familiare di colore blu"
      annoImmatricolazione:
        type: integer
        format: int32
        example: 2021