swagger: "2.0"
info: 
  title: Esercizio 3 Esame 28/05/2024
  description: API per la gestione del giro d'Italia
  version: 1.0.0
paths:
  /giro/edizione/{idEdizione}/tappe:
    get:
      description: "Get di tutte le tappe con una certa lunghezza"  
      operationId: getTappeFromEdizione
      parameters:
        - in: path
          required: true
          name: idEdizione
          type: integer
          format: int32
        - in: query
          required: false
          name: lunghezzaTappe
          type: integer
          format: int32
      responses:
        200:
          description: "Success tappe individuate"
          schema:
            type: array
            items: 
              $ref: "#/definitions/Tappa"
        400:
          description: "Failed parametri in input non corretti"
    post: 
      description: "Add di una tappa all'edizione"
      operationId: "AddTappa"
      parameters: 
        - in: path 
          required: true
          name: idEdizione
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovaTappa
          schema: 
            type: object
            $ref: "#/definitions/Tappa"
      responses:
        200:
          description: "Success tappa aggiunta"
          schema: 
            type: object
            $ref: "#/definitions/Tappa"
        400:
          description: "Failed parametri in input non corretti"
  /giro/edizione/{idEdizione}:
    put:
      description: "Update data di fine di un'edizione"
      operationId: updateDataFineTappa
      parameters: 
        - in: path 
          required: true
          name: idEdizione
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovaDataFine
          schema:
            type: string
            format: date
            example: "18/05/2024"
      responses:
        200:
          description: "Success data di fine aggiornata"
        400: 
          description: "Failed parametri in input non corretti"
definitions: 
  Edizione:
    type: object
    required:
      - id
      - dataInizio
      - dataFine
      - tappe
    properties:
      id:
        type: integer
        format: int32
        example: 2024
      dataInizio:
        type: string
        format: date 
        example: "16/05/2024"
      dataFine:
        type: string
        format: date 
        example: "16/06/2024"
      tappe:
        type: array
        items:
          $ref: "#/definitions/Tappa"
  Tappa:
    type: object
    required: 
      - id
      - nome 
      - lunghezza
    properties: 
      id: 
        type: integer
        format: int32
        example: 1
      nome: 
        type: string
        example: "Rimini-Bologna"
      lunghezza:
        type: integer
        format: int32
        example: 201