swagger: "2.0"
info:
  title: "Esercizio 3 Simulazione di Esame"
  description: "API per la gestione di una collezione di serie televisive"
  version: 1.0.0
paths:
  /collezione/series/:
    get:  
      description: "Get di tutte le serie di un certo genere e pubblicate ad una certa data"
      operationId: getSerieFromGenereAndDataPubblicazione
      parameters:
        - in: query
          required: true
          name: genere
          type: string
          enum: 
            - "Animazione"
            - "Avventura"
            - "Commedia"
            - "Horror"
            - "Documentario"
        - in: query
          required: true
          name: dataPubblicazione
          type: string
          format: date
      responses:
        "200":
          description: "Success"
          schema:
            type: array
            items:  
              $ref: "#/definitions/Serie"
        "400":
          description: "Failed parametri in input non corretti"
  /collezione/series/{idSerie}:
    post:
      description: "Add di un episodio ad una serie"
      operationId: addEpisodio
      parameters:
        - in: path
          required: true
          name: idSerie
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovoEpisodio
          schema: 
            type: object
            $ref: "#/definitions/Episodio"
      responses:
        "200":
          description: "Success"
          schema:
            type: object 
            $ref: "#/definitions/Episodio"
        "400":
          description: "Failed parametri in input non corretti"
  /collezione/series/{idSerie}/episodi/{numeroEpisodio}:
    put:
      description: "Uodate titolo di un episodio di una serie"
      operationId: updateTitoloEpisodio
      parameters:
        - in: path
          required: true
          name: idSerie
          type: integer
          format: int32
        - in: path
          required: true
          name: numeroEpisodio
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovoTitolo
          schema: 
            type: string
            example: "La nuova scoperta"
      responses:
        "200":
          description: "Success"
        "400":
          description: "Failed parametri in input non corretti"     
definitions:
  Serie:
    type: object
    required: 
      - id
      - titolo 
      - dataPubblicazione
      - episodi
      - genere
    properties:
      id: 
        type: integer
        format: int32
        example: 27
      titolo:
        type: string
        example: "Stranger Things"
      dataPubblicazione:
        type: string
        format: date
        example: "2024-06-07"
      episodi:
        type: array
        items:
          $ref: "#/definitions/Episodio"
      genere:
        type: string
        enum: 
         - "Animazione"
         - "Avventura"
         - "Commedia"
         - "Horror"
         - "Documentario"
        example: "Horror"
  Episodio:
    type: object
    required: 
      - numero
      - titolo 
    properties:
      numero: 
        type: integer
        format: int32
        example: 1
      titolo:
        type: string
        example: "La trappola per topi"