swagger: "2.0"
info: 
  title: "API per la gestione di un sistema di messagistica"
  version: 1.0.0
paths:
  /sistema/sessioni/{idSessione}/messaggi/:
    get:
      description: "Get di tutti i messaggi aventi un certo score"
      operationId: getMessaggiByScore
      parameters:
        - in: path
          required: true
          name: idSessione
          type: integer
          format: int32
        - in: query
          required: true
          name: scoreMessaggi
          type: integer
          format: int32
      responses:
        '200':
          description: "Success messaggi individuati"
          schema:
            type: array
            items:
              $ref: "#/definitions/Messaggio"
        '400':
          description: "Failed parametri di input non corretti"
  /sistema/sessioni/{idSessione}/:
    post:
      description: "Add di un messaggio alla sessione"
      operationId: addMessaggio
      parameters: 
        - in: path
          required: true
          name: idSessione
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovoMessaggio
          schema:
            type: object
            $ref: "#/definitions/Messaggio"
      responses:    
        '200':
          description: "Success messaggi aggiunto"
          schema:
            type: object
            $ref: "#/definitions/Messaggio"
        '400':
          description: "Failed parametri di input non corretti"
  /sistema/sessioni/{idSessione}/messaggi/{idMessaggio}/: 
    put:
      description: "Update dello score di un messaggio"
      operationId: updateScoreMessaggio
      parameters:
        - in: path
          required: true
          name: idSessione
          type: integer
          format: int32
        - in: path
          required: true
          name: idMessaggio
          type: integer
          format: int32
        - in: body
          required: true
          name: nuovoScore
          schema:
            type: integer
            format: int32
      responses:  
        '200':
          description: "Success score del messaggio aggiornato"
        '400':
          description: "Failed parametri di input non corretti"
definitions:
  Sessione:
    type: object
    required:
      - idSessione
      - dataSessione
    properties:
      idSessione:
        type: integer
        format: int32
        example: 1
      dataSessione:
        type: string
        format: date
        example: "01/01/2024"
  Messaggio:
    type: object
    required: 
      - idMessaggio
      - testoMessaggio
      - scoreMessaggio
    properties: 
      idMessaggio: 
        type: integer
        format: int32
        example: 7
      testoMessaggio:
        type: string
        example: "Ciao, come stai?"
      scoreMessaggio:
        type: integer
        format: int32
        enum: 
          - 1 
          - 2
          - 3
          - 4 
          - 5
        example: 3